---
abstract: 'Return a DBIC row based on the current Catalyst context'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst: '5.90060'
  Catalyst::Model::DBIC::Schema: '0.65'
  DBIx::Class: '0.082820'
  Test::DBIx::Class: '0.43'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.036, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-TraitFor-Model-DBIC-Schema-Result
requires:
  Moose: '2.1403'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-TraitFor-Model-DBIC-Schema-Result/issues
  homepage: https://github.com/jjn1056/Catalyst-TraitFor-Model-DBIC-Schema-Result
  repository: https://github.com/jjn1056/Catalyst-TraitFor-Model-DBIC-Schema-Result.git
version: '0.003'
